// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package orderclient

import (
	"context"

	"mall/service/order/rpc/order"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	CreateRequest  = order.CreateRequest
	RemoveResponse = order.RemoveResponse
	DetailRequest  = order.DetailRequest
	ListRequest    = order.ListRequest
	ListResponse   = order.ListResponse
	PaidRequest    = order.PaidRequest
	CreateResponse = order.CreateResponse
	UpdateRequest  = order.UpdateRequest
	UpdateResponse = order.UpdateResponse
	RemoveRequest  = order.RemoveRequest
	DetailResponse = order.DetailResponse
	PaidResponse   = order.PaidResponse

	Order interface {
		Create(ctx context.Context, in *CreateRequest) (*CreateResponse, error)
		Update(ctx context.Context, in *UpdateRequest) (*UpdateResponse, error)
		Remove(ctx context.Context, in *RemoveRequest) (*RemoveResponse, error)
		Detail(ctx context.Context, in *DetailRequest) (*DetailResponse, error)
		List(ctx context.Context, in *ListRequest) (*ListResponse, error)
		Paid(ctx context.Context, in *PaidRequest) (*PaidResponse, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) Create(ctx context.Context, in *CreateRequest) (*CreateResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.Create(ctx, in)
}

func (m *defaultOrder) Update(ctx context.Context, in *UpdateRequest) (*UpdateResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.Update(ctx, in)
}

func (m *defaultOrder) Remove(ctx context.Context, in *RemoveRequest) (*RemoveResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.Remove(ctx, in)
}

func (m *defaultOrder) Detail(ctx context.Context, in *DetailRequest) (*DetailResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.Detail(ctx, in)
}

func (m *defaultOrder) List(ctx context.Context, in *ListRequest) (*ListResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.List(ctx, in)
}

func (m *defaultOrder) Paid(ctx context.Context, in *PaidRequest) (*PaidResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.Paid(ctx, in)
}
